<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit979e4f998bc9099a15d535b062367e3b
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SpinningSquid\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SpinningSquid\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit979e4f998bc9099a15d535b062367e3b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit979e4f998bc9099a15d535b062367e3b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit979e4f998bc9099a15d535b062367e3b::$classMap;

        }, null, ClassLoader::class);
    }
}
